# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ks < Formula
  desc ""
  homepage ""
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/isksss/ks/releases/download/v1.0.1/ks_Darwin_x86_64.tar.gz"
      sha256 "e4f2c20d5411140f54a87297f8fb516575cc336dffdd2e6e29703d5ebabbe7b7"

      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/isksss/ks/releases/download/v1.0.1/ks_Darwin_arm64.tar.gz"
      sha256 "c6adde630eafe74052a7012b6b1bb74e52eec8dfe865aa56c7ee85445d90c5ab"

      def install
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/isksss/ks/releases/download/v1.0.1/ks_Linux_x86_64.tar.gz"
      sha256 "0e4df878f7d7b65f77b51b70946f5797960b32d01a79af41f83ad4673693c015"

      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/isksss/ks/releases/download/v1.0.1/ks_Linux_arm64.tar.gz"
      sha256 "b509ee9b1f15706dd96265bbcc5f2f485b41034be3efeb9b38671870cfcffe83"

      def install
        bin.install "ks"
      end
    end
  end
end
